# Generated by Django 4.0 on 2022-02-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, verbose_name='用户名'),
        ),
    ]
