# Generated by Django 4.0 on 2022-02-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_checkreport_healthmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department_name', models.TextField()),
                ('department_position', models.TextField()),
                ('check_agent', models.TextField()),
                ('check_item', models.TextField(null=True)),
                ('announcement', models.TextField()),
                ('check_time', models.DateTimeField(null=True)),
                ('check_number', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='checkreport',
            name='title',
        ),
        migrations.DeleteModel(
            name='HealthModel',
        ),
        migrations.AddField(
            model_name='checkreport',
            name='check_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.checkitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.region', verbose_name='region'),
        ),
    ]
