# Generated by Django 4.0 on 2022-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_checkproject_rename_check_item_checkitem_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkproject',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkproject',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
