# Generated by Django 4.0 on 2022-02-17 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_alter_checkproject_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_doctor',
                                    to='api.user'),
        ),
    ]
