# Generated by Django 4.0 on 2022-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_checkreport_remove_checkitem_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.AlterField(
            model_name='user',
            name='card_id',
            field=models.CharField(max_length=30, null=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号码'),
        ),
    ]
