# Generated by Django 4.0 on 2022-02-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_timesheet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkproject',
            options={'verbose_name': '检查项目', 'verbose_name_plural': '检查项目'},
        ),
        migrations.AlterModelOptions(
            name='checkreport',
            options={'verbose_name': '检查报告', 'verbose_name_plural': '检查报告'},
        ),
        migrations.AddField(
            model_name='timesheet',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkproject',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
    ]
