# Generated by Django 4.0 on 2022-02-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_remove_checkitem_check_time_checkitem_check_am_pm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['time', 'am'], 'verbose_name': '时间表', 'verbose_name_plural': '时间表'},
        ),
        migrations.RemoveField(
            model_name='checkitem',
            name='check_report',
        ),
        migrations.AddField(
            model_name='checkitem',
            name='status',
            field=models.CharField(choices=[('已完成体检报告', 'Finished'), ('未完成体检报告', 'Unfinished'), ('等待检查', 'Waiting')],
                                   default='Waiting', max_length=100),
        ),
        migrations.AddField(
            model_name='checkreport',
            name='checkitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_user',
                                    to='api.checkitem', verbose_name='检查用户'),
        ),
    ]
