# Generated by Django 4.0 on 2022-02-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_timesheet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkreport',
            name='checkitem',
        ),
        migrations.AddField(
            model_name='checkitem',
            name='check_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkitem', to='api.checkreport', verbose_name='检查报告'),
        ),
    ]
