# Generated by Django 4.0 on 2022-02-18 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_checkreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='am',
            field=models.PositiveIntegerField(default=20, verbose_name='上午访问人数'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='pm',
            field=models.PositiveIntegerField(default=20, verbose_name='下午访问人数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
