# Generated by Django 4.0 on 2022-02-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_timesheet_am_alter_timesheet_pm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkproject',
            name='credit',
            field=models.IntegerField(null=True, verbose_name='预算案例'),
        ),
        migrations.AlterField(
            model_name='checkproject',
            name='department_name',
            field=models.TextField(verbose_name='负责科室'),
        ),
        migrations.AlterField(
            model_name='checkproject',
            name='name',
            field=models.CharField(max_length=20, verbose_name='活动名称'),
        ),
    ]
