# Generated by Django 4.0 on 2022-02-19 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_alter_checkproject_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='count',
        ),
        migrations.AddField(
            model_name='checkitem',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
        migrations.AddField(
            model_name='region',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='region',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='region',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checkproject',
            name='check_agent',
            field=models.TextField(verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='checkproject',
            name='check_item',
            field=models.TextField(null=True, verbose_name='检查范围'),
        ),
        migrations.AlterField(
            model_name='checkproject',
            name='department_position',
            field=models.TextField(verbose_name='科室位置'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
