# Generated by Django 4.0 on 2022-02-19 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0022_remove_region_count_checkitem_region_region_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '投放区域', 'verbose_name_plural': '投放区域'},
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='女', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='checkitem',
            name='check_date',
            field=models.DateTimeField(null=True, verbose_name='预计开始时间'),
        ),
        migrations.AlterField(
            model_name='checkitem',
            name='status',
            field=models.CharField(choices=[('Finished', '已完成体检报告'), ('Unfinished', '未完成体检报告'), ('Waiting', '等待检查')],
                                   default='Waiting', max_length=100, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='checkreport',
            name='status',
            field=models.CharField(choices=[('Finished', '报告已完成'), ('Unfinished', '报告未填写')], default='Unfinished',
                                   max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=10, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='region',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='预算案例'),
        ),
        migrations.AlterField(
            model_name='region',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='投放区域'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user',
                                    verbose_name='发送人'),
        ),
        migrations.AlterField(
            model_name='region',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
