# Generated by Django 4.0 on 2022-02-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_checkreport_result_checkreport_body_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='left_credit',
            field=models.IntegerField(default=0, verbose_name='剩余份额'),
        ),
        migrations.AlterField(
            model_name='checkreport',
            name='status',
            field=models.CharField(choices=[('Finished', '报告已完成'), ('Unfinished', '报告未填写')], default='Unfinished', max_length=50, verbose_name='状态'),
        ),
    ]
