# Generated by Django 4.0 on 2022-02-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0028_remove_checkitem_check_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='check_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='checkitem', to='api.checkreport', verbose_name='检查报告'),
        ),
    ]
