# Generated by Django 4.0 on 2022-02-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_checkitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='check_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkitem', to='api.checkreport', verbose_name='检查报告'),
        ),
    ]
